= Demo für Spring Boot Microservice

In diesem Gradle-basierten Projekt wird gezeigt, wie mit wenig Code ein kompletter Microservice mit voller CRUD
Funktionalität erstellt werden.

== Technologien und Anforderungen
Dieses Projekt nutzt:

- Java 21
- Spring Boot 3.4.5
- Gradle 8.13
- Lombok
- H2

Es sollte auf allen Umgebungen, sogar Windows, ausführbar sein, solange `java` verfügbar ist.

== Wie ausführen?
Im Wurzelverzeichnis kann `./gradlew clean build bootRun` ausgeführt werden. Danach stehen die REST Endpunkte unter
`http://localhost:8080/api` zur Verfügung.

Daten werden in einer in-memory H2 Datenbank gespeichert. Es wird also nichts persistiert.
Die Initialisierung geschieht mittels der link:src/main/resources/data.sql[data.sql] Datei.

Zur Laufzeit kann über http://localhost:8080/h2-console die H2 Konsole aufgerufen werden.

== Beispiel-Requests
Es gibt für jeden Request-Typ ein eigenes http-Client Script unter link:./src/main/http/[src/main/http].

Hier aber auch noch eine Übersicht für die Verwendung von `curl` bzw. (unter Windows PowerShell) mit `Invoke-WebRequest`.

In den Beispielen verwende ich `jq` zusammen mit `curl`. Das formatiert in diesem Fall nur die Antwort. Wenn es nicht installiert sein sollte, kann es natürlich weggelassen werden.

[,bash]
.GET Request für alle verfügbaren Produkte
----
curl -H "Content-Type: application/json" http://localhost:8080/api/products | jq
----

[,powershell]
.GET Request für alle verfügbaren Produkte (Windows)
----
Invoke-WebRequest -Uri "http://localhost:8080/api/products/" -Method GET | Select-Object -ExpandProperty Content
----

[,bash]
.GET Request für spezifisches Produkt
----
curl -H "Content-Type: application/json" http://localhost:8080/api/products/1 | jq
----

[,powershell]
.GET Request für alle verfügbaren Produkte (Windows)
----
Invoke-WebRequest -Uri "http://localhost:8080/api/products/1" -Method GET | Select-Object -ExpandProperty Content
----

[,bash]
.POST Request, um neues Produkt hinzuzufügen
----
curl -X POST http://localhost:8080/api/products \
  -H "Content-Type: application/json" \
  -d '{"name":"Tablet","description":"New tablet model","price":499.99}'
----

[,powershell]
.POST Request, um neues Produkt hinzuzufügen
----
$body = @{
  name = "Tablet"
  description = "New tablet model"
  price = 499.99
} | ConvertTo-Json
Invoke-WebRequest -Uri "http://localhost:8080/api/products" -Method POST -Body $body -ContentType "application/json" | Select-Object -ExpandProperty Content
----

[,bash]
.DELETE Request
----
curl -X DELETE http://localhost:8080/api/products/1
----

[,powershell]
.DELETE Request (Windows)
----
Invoke-WebRequest -Uri "http://localhost:8080/api/products/1" -Method DELETE
----

== Docker
Das Projekt beinhaltet ein simples link:Dockerfile[Dockerfile].

.Image bauen
----
docker build -t product-service:latest .
----

.Container bauen und ausführen (Beenden mit Ctrl+C)
----
## Container wird nach beenden gelöscht (--rm)
docker run --rm --name product-service-tmp -p 8080:8080 product-service:latest
----

== Kubernetes
Natürlich sollten wir jetzt auch in Kubernetes deployen.

Lokal benutzen wir https://minikube.sigs.k8s.io/docs/[Minikube]. Dies kann wie folgt gestartet werden:

.Minikube auf MacOS starten
----
minikube start --cpus=4 --memory=8g --driver=docker
----

.Minikube auf WIndows starten
----
minikube start --cpus=4 --memory=8g --driver=hyperv
----

Dann setzen wir die Umgebung so, dass wir innerhalb von Minikube bauen:

.MacOS Umgebung für Minikube Build setzen
----
eval $(minikube docker-env)
----

[,powershell]
.Windows Umgebung für Minikube Build setzen
----
minikube docker-env | Invoke-Expression
----

und dann können wir bauen:

.Docker Build wie zuvor
----
docker build -t product-service:latest .
----

Und dann geht es ans Deployment:

.Deployment ins Minikube
----
kubectl apply -f k8s/k8s-deployment.yml
kubectl apply -f k8s/k8s-service.yml
----


.Zugriff auf Services
[,bash]
----
minikube service product-service --url
----

.Logs anzeigen
[,bash]
----
kubectl logs -f deployment/product-service
----

== Event-Driven-Development Beispiel mit RabbitMQ
In der link:docker-compose.yml[docker-compose.yml] ist alles so konfiguriert, dass ein RabbitMQ gestartet wird, der lokal unter http://localhost:5672 (Username & Passwort: _guest_) verfügbar ist.

Das Starten ist denkbar einfach:

.Starten von RabbitMQ und der Anwendung in Docker
----
docker compose up
----

Beim Erzeugen von neuen Produkten wird nun ein Event veröffentlicht. Auf dieses lauscht `ProductEventListener` und schreibt ins Log:

.Beispiel Log-Zeile, wenn Produkt erzeugt wurde
----
product-service-1  | 📦 Neues Produkt erstellt: ID=4, Name=circuit
----

Am Einfachsten ist es, einfach link:src/main/http/02_add_product.http[02_add_product.http] auszuführen, um zufällige Produkte hinzuzufügen.

Beendet werden kann entweder mit _Ctrl+C_ oder, wenn `docker compose up -d` ausgeführt wurde und es damit im Hintergrund läuft, mit `docker compose down`.

== Logging & Monitoring
In der link:docker-compose.monitoring.yml[] ist eine Konfiguration hinterlegt, mit der wir folgende Services bekommen:

* Elastic-Stack mit
** Logstash
** http://localhost:9200[Elasticsearch]
** http://localhost:5601[Kibana]
* http://localhost:9090[Prometheus]
* http://localhost:3000[Grafana]
* http://localhost:5672[RabbitMQ]

In den gleichnamigen Ordnern im Wurzelverzeichnis des Projektes liegen einige Konfigurationen.

Es wird auch kontinuierlich `DemoDataGenerator` aufgerufen, welcher Daten generiert. Das erzeugt Logs, welche dann in den Statistiken auftauchen.

Damit in Kibana etwas zu sehen ist. warte kurz, bis alles fertig gestartet ist. Dann

1. Öffne http://localhost:5601[Kibana]
2. Navigiere zu **Stack Management** -> **Index Management** -> **Create Index**
3. Gib `product-service-*` als Pattern ein
4. Wähle `@timestamp` als Zeitfeld
5. Klicke auf **Create index pattern**

Danach, ebenfalls im **Stack Management**:

1. Navigiere zu **Saved Objects**
2. Klicke oben rechts auf **Import**
3. Lade die Datei link:kibana/dashboards/product-service-dashbaords.ndjson[product-service-dashbaords.ndjson] hoch
4. Speichere

Nun sollte under **Analytics** -> **Dashboards** das neue _Product Service Dashboard_ verfügbar sein.

== Jenkins
Am Einfachsten ist es, Jenkins via homebrew installieren:

.Jenkins LTS Version via homebrew installieren
----
brew install jenkins-lts
----

.Starten und Stoppen des Dienstes
----
brew service start jenkins-lts
brew service stop jenkins-lts
----

Im link:Jenkinsfile[] ist ein einfaches Build definiert.
Dieses setzt voraus:

1. Das ein `JDK 21` (wird in Jenkinsfile referenziert) definiert ist und auf das `JAVA_HOME` eines JDK 21 zeigt
2. In den globalen Einstellungen sollte die Umgebungsvariable `PATH` auf `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin` gesetzt sein (beim Mac)
3. Credentials für git sind hinterlegt
4. Kubernetes "Credentials" hinterlegen:
  - Jenkins verwalten -> Credentials -> System -> Global credentials
  - Credentials hinzufügen
  - Secret file
  - `ID` auf `minikube-config` setzen (wird in Jenkinsfile referenziert!)
  - `~/.kube/config` hinzufügen (oder Kopie davon erstellen und hier hinterlegen)
  - Beschreibung: `Minikube Kubernetes Config`

Dann kann die Pipeline erstellt werden:

1. Neues Item -> Pipeline
2. Namen eingeben
3. Bei Pipeline Definition "Pipeline script from SCM" wählen
4. SCM -> Git
5. Repository URL -> URL
6. Credentials auswählen, die vorhin dafür angelegt wurden
7. Branch Specified: `*/main`
8. Speichern
9. Build starten

