apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - port: 8080
      targetPort: 8080
      # Optional: Du kannst einen spezifischen NodePort festlegen (30000-32767)
      # nodePort: 30080
  type: NodePort
